INSERT INTO `tallas` (`talla`) VALUES ( "CH");
INSERT INTO `tallas` (`talla`) VALUES ( "M");
INSERT INTO `tallas` (`talla`) VALUES ( "G");
INSERT INTO `usuarios` (`nombre_completo`,`nombres_de_usuarios`,`telefono`,`email`,`contrasenia`)VALUES ("Raygoza Zamudio Rafael","Rafa","3330349623", "raygoza.zamudio.rafael@gmail.com","contrasenia segura");
INSERT INTO `usuarios` (`nombre_completo`,`nombres_de_usuarios`,`telefono`,`email`,`contrasenia`)VALUES("Juan Marcos Gonzalez Romo","JuanMGonRo","3316935436","gonzalezromojm@gmail.com","juanito1997");
INSERT INTO `usuarios` (`nombre_completo`,`nombres_de_usuarios`,`telefono`,`email`,`contrasenia`)VALUES("Karen Chavando Perez","KarenCP","3316935296","chavandokaren09@gmail.com","karen1234");
INSERT INTO `usuarios` (`nombre_completo`,`nombres_de_usuarios`,`telefono`,`email`,`contrasenia`)VALUES("María Fernanda Rosales Ortega", "FerRos","5544517592","fernanda.rosales.ortega@gmail.com","F312066064");
INSERT INTO `usuarios` (`nombre_completo`,`nombres_de_usuarios`,`telefono`,`email`,`contrasenia`)VALUES("Alejandro Morales","alex19","7295183114","moralesa043@gmail.com","1234");
INSERT INTO `products` (`nombre`,`precio`,`categoria`,`enlaceimagen`)VALUES ("Denji",150,1, "https://i.ibb.co/qpPQSvB/denji-pld-mar.png");
INSERT INTO `products` (`nombre`,`precio`,`categoria`,`enlaceimagen`)VALUES ("Denji",150,1, "https://i.ibb.co/CsCttwR/denji-pld-neg.png");
INSERT INTO `products` (`nombre`,`precio`,`categoria`,`enlaceimagen`)VALUES ("Denji",150,2, "https://i.ibb.co/Qp3fKRS/denji-pl-neg.png");
INSERT INTO `products` (`nombre`,`precio`,`categoria`,`enlaceimagen`)VALUES ("Denji",150,2, "https://i.ibb.co/Nx4SrXt/denji-pl-gris.png");
INSERT INTO `products` (`nombre`,`precio`,`categoria`,`enlaceimagen`)VALUES ("Denji",300,3, "https://i.ibb.co/VLkYhFp/denji-sud-neg.png");
INSERT INTO `products` (`nombre`,`precio`,`categoria`,`enlaceimagen`)VALUES ("Denji",300,3, "https://i.ibb.co/tJLkDX7/denji-sud-gris.png");
INSERT INTO `products` (`nombre`,`precio`,`categoria`,`enlaceimagen`)VALUES ("Izuku Midoriya",150,1, "https://i.ibb.co/XFDg6Zt/deku-pld-mar.png");
INSERT INTO `products` (`nombre`,`precio`,`categoria`,`enlaceimagen`)VALUES ("Izuku Midoriya",150,1, "https://i.ibb.co/VVPwTjw/deku-pld-neg.png");
INSERT INTO `products` (`nombre`,`precio`,`categoria`,`enlaceimagen`) VALUES ("Izuku Midoriya",150,2, "https://i.ibb.co/jJbpGS9/deku-pl-gris.png");
INSERT INTO `products` (`nombre`,`precio`,`categoria`,`enlaceimagen`) VALUES ("Izuku Midoriya",150,2, "https://i.ibb.co/SvxjQ70/deku-pl-neg.png");
INSERT INTO `products` (`nombre`,`precio`,`categoria`,`enlaceimagen`) VALUES ("Izuku Midoriya",300,3, "https://i.ibb.co/xjYR6Zh/deku-sud-gris.png");
INSERT INTO `products` (`nombre`,`precio`,`categoria`,`enlaceimagen`) VALUES ("Izuku Midoriya",300,3, "https://i.ibb.co/8bZ5Pcr/deku-sud-neg.png");
INSERT INTO `products` (`nombre`,`precio`,`categoria`,`enlaceimagen`) VALUES ("Tanjiro Kamado",150,1, "https://i.ibb.co/0fXpTq5/tanjiro-pld-mar.png");
INSERT INTO `products` (`nombre`,`precio`,`categoria`,`enlaceimagen`) VALUES ("Tanjiro Kamado",150,1, "https://i.ibb.co/6RZYwyW/tanjiro-pld-neg.png");
INSERT INTO `products` (`nombre`,`precio`,`categoria`,`enlaceimagen`) VALUES ("Tanjiro Kamado",150,2, "https://i.ibb.co/P4RnXjM/tanjiro-pl-gris.png");
INSERT INTO `products` (`nombre`,`precio`,`categoria`,`enlaceimagen`) VALUES ("Tanjiro Kamado",150,2, "https://i.ibb.co/H2BLXD0/tanjiro-pl-neg.png");
INSERT INTO `products` (`nombre`,`precio`,`categoria`,`enlaceimagen`) VALUES ("Tanjiro Kamado",300,3, "https://i.ibb.co/FhTwqyv/tanjiro-sud-gris.png");
INSERT INTO `products` (`nombre`,`precio`,`categoria`,`enlaceimagen`) VALUES ("Tanjiro Kamado",300,3, "https://i.ibb.co/BTfHk12/tanjiro-sud-neg.png");
INSERT INTO `products` (`nombre`,`precio`,`categoria`,`enlaceimagen`) VALUES ("Monkey D. Luffy",150,1, "https://i.ibb.co/sFTD6XM/luffy-pld-neg.png");
INSERT INTO `products` (`nombre`,`precio`,`categoria`,`enlaceimagen`) VALUES ("Monkey D. Luffy",150,1, "https://i.ibb.co/sFTD6XM/luffy-pld-neg.png");
INSERT INTO `products` (`nombre`,`precio`,`categoria`,`enlaceimagen`) VALUES ("Monkey D. Luffy",150,2, "https://i.ibb.co/0qcBRrJ/luffi-pl-neg.png");
INSERT INTO `products` (`nombre`,`precio`,`categoria`,`enlaceimagen`) VALUES ("Monkey D. Luffy",150,2, "https://i.ibb.co/zNk7v2W/luffy-pl-gris.png");
INSERT INTO `products` (`nombre`,`precio`,`categoria`,`enlaceimagen`) VALUES ("Monkey D. Luffy",300,3, "https://i.ibb.co/g7WGTLC/luffy-sud-neg.png");
INSERT INTO `products` (`nombre`,`precio`,`categoria`,`enlaceimagen`) VALUES ("Monkey D. Luffy",300,3, "https://i.ibb.co/fk0Zk7q/luffy-sud-gris.png");
INSERT INTO `products` (`nombre`,`precio`,`categoria`,`enlaceimagen`) VALUES ("Eren Yeager",150,1, "https://i.ibb.co/6gz6ZL7/eren-pld-neg.png");
INSERT INTO `products` (`nombre`,`precio`,`categoria`,`enlaceimagen`) VALUES ("Eren Yeager",150,1, "https://i.ibb.co/Qjj5z5D/eren-pld-mar.png");
INSERT INTO `products` (`nombre`,`precio`,`categoria`,`enlaceimagen`) VALUES ("Eren Yeager",150,2, "https://i.ibb.co/Vj5P0VV/eren-pl-neg.png");
INSERT INTO `products` (`nombre`,`precio`,`categoria`,`enlaceimagen`) VALUES ("Eren Yeager",150,2, "https://i.ibb.co/pPXdkJG/eren-pl-gris.png");
INSERT INTO `products` (`nombre`,`precio`,`categoria`,`enlaceimagen`) VALUES ("Eren Yeager",300,3, "https://i.ibb.co/Gxcy56R/eren-sud-neg.png");
INSERT INTO `products` (`nombre`,`precio`,`categoria`,`enlaceimagen`) VALUES ("Eren Yeager",300,3, "https://i.ibb.co/TB5DHmv/eren-sud-gris.png");
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (1, 1);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (1, 2);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (1, 3);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (2, 1);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (2, 2);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (2, 3);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (3, 1);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (3, 2);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (3, 3);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (4, 1);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (4, 2);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (4, 3);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (5, 1);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (5, 2);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (5, 3);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (6, 1);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (6, 2);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (6, 3);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (7, 1);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (7, 2);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (7, 3);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (8, 1);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (8, 2);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (8, 3);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (9, 1);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (9, 2);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (9, 3);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (10, 1);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (10, 2);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (10, 3);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (11, 1);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (11, 2);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (11, 3);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (12, 1);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (12, 2);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (12, 3);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (13, 1);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (13, 2);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (13, 3);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (14, 1);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (14, 2);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (14, 3);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (15, 1);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (15, 2);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (15, 3);
INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (16, 1);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (16, 2);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (16, 3);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (17, 1);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (17, 2);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (17, 3);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (18, 1);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (18, 2);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (18, 3);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (19, 1);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (19, 2);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (19, 3);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (20, 1);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (20, 2);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (20, 3);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (21, 1);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (21, 2);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (21, 3);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (22, 1);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (22, 2);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (22, 3);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (23, 1);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (23, 2);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (23, 3);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (24, 1);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (24, 2);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (24, 3);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (25, 1);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (25, 2);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (25, 3);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (26, 1);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (26, 2);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (26, 3);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (27, 1);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (27, 2);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (27, 3);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (28, 1);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (28, 2);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (28, 3);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (29, 1);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (29, 2);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (29, 3);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (30, 1);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (30, 2);
 INSERT INTO `producto_talla` (`id_product`, `id_product_size`) VALUES (30, 3);
 INSERT INTO `carrito` (`enlaceimagen`,`nombre`,`precio`,`talla`,`fk_id_User`) VALUES ("https://i.ibb.co/TB5DHmv/eren-sud-gris.png","Eren Yaher",300,"M",1);
 INSERT INTO `carrito` (`enlaceimagen`,`nombre`,`precio`,`talla`,`fk_id_User`) VALUES ("https://i.ibb.co/TB5DHmv/eren-sud-gris.png","Eren Yaher",300,"G",1);